/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.unifio.barbersoft;

import EnderecoViaCep.Endereco;
import EnderecoViaCepService.ViaCepService;
import LoginBarbersoftController.loginControler;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author educo
 */
public class telaCadastroBarbearia extends javax.swing.JFrame {

    /**
     * Creates new form telaCadastroBarbearia
     */
    public telaCadastroBarbearia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNomeFanstasia = new javax.swing.JLabel();
        lbCnpj = new javax.swing.JLabel();
        lbAdmTelefone = new javax.swing.JLabel();
        lbAdmEmail = new javax.swing.JLabel();
        lbAdmSenha = new javax.swing.JLabel();
        lbAdmRepSenha = new javax.swing.JLabel();
        lbAdmNomeRepres = new javax.swing.JLabel();
        txtAdmNomeF = new javax.swing.JTextField();
        ftxtAdmCnpj = new javax.swing.JFormattedTextField();
        ftxtAdmTelefone = new javax.swing.JFormattedTextField();
        txtAdmEmail = new javax.swing.JTextField();
        pwAdmSenha = new javax.swing.JPasswordField();
        pwAdmReSenha = new javax.swing.JPasswordField();
        txtAdmRepres = new javax.swing.JTextField();
        lbAdmCep = new javax.swing.JLabel();
        lbAdmCidade = new javax.swing.JLabel();
        txtAdmCidade = new javax.swing.JTextField();
        ftxtAdmCEP = new javax.swing.JFormattedTextField();
        btAdmBuscaCep = new javax.swing.JButton();
        btAdmCadastrar = new javax.swing.JButton();
        btAdmCancel = new javax.swing.JButton();
        lbCadAdmBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        lbNomeFanstasia.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        lbNomeFanstasia.setText("Nome Fantasia: ");
        getContentPane().add(lbNomeFanstasia);
        lbNomeFanstasia.setBounds(10, 70, 150, 30);

        lbCnpj.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        lbCnpj.setText("CNPJ:");
        getContentPane().add(lbCnpj);
        lbCnpj.setBounds(80, 110, 60, 30);

        lbAdmTelefone.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        lbAdmTelefone.setText("Telefone:");
        getContentPane().add(lbAdmTelefone);
        lbAdmTelefone.setBounds(60, 150, 90, 30);

        lbAdmEmail.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        lbAdmEmail.setText("E-mail:");
        getContentPane().add(lbAdmEmail);
        lbAdmEmail.setBounds(80, 190, 70, 30);

        lbAdmSenha.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        lbAdmSenha.setText("Senha:");
        getContentPane().add(lbAdmSenha);
        lbAdmSenha.setBounds(80, 230, 60, 30);

        lbAdmRepSenha.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        lbAdmRepSenha.setText("Repetir Senha:");
        getContentPane().add(lbAdmRepSenha);
        lbAdmRepSenha.setBounds(10, 270, 130, 30);

        lbAdmNomeRepres.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        lbAdmNomeRepres.setText("Representante:");
        getContentPane().add(lbAdmNomeRepres);
        lbAdmNomeRepres.setBounds(10, 310, 150, 30);

        txtAdmNomeF.setFont(new java.awt.Font("Perpetua", 0, 20)); // NOI18N
        getContentPane().add(txtAdmNomeF);
        txtAdmNomeF.setBounds(150, 70, 520, 30);

        try {
            ftxtAdmCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtAdmCnpj.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        getContentPane().add(ftxtAdmCnpj);
        ftxtAdmCnpj.setBounds(150, 110, 520, 30);

        try {
            ftxtAdmTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtAdmTelefone.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        getContentPane().add(ftxtAdmTelefone);
        ftxtAdmTelefone.setBounds(150, 150, 520, 30);

        txtAdmEmail.setFont(new java.awt.Font("Perpetua", 0, 20)); // NOI18N
        getContentPane().add(txtAdmEmail);
        txtAdmEmail.setBounds(150, 190, 520, 30);

        pwAdmSenha.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        pwAdmSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwAdmSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(pwAdmSenha);
        pwAdmSenha.setBounds(150, 230, 520, 30);

        pwAdmReSenha.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        pwAdmReSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwAdmReSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(pwAdmReSenha);
        pwAdmReSenha.setBounds(150, 270, 520, 30);

        txtAdmRepres.setFont(new java.awt.Font("Perpetua", 0, 20)); // NOI18N
        getContentPane().add(txtAdmRepres);
        txtAdmRepres.setBounds(150, 310, 520, 30);

        lbAdmCep.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        lbAdmCep.setText("CEP:");
        getContentPane().add(lbAdmCep);
        lbAdmCep.setBounds(90, 350, 69, 40);

        lbAdmCidade.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        lbAdmCidade.setText("Cidade:");
        getContentPane().add(lbAdmCidade);
        lbAdmCidade.setBounds(70, 390, 69, 40);

        txtAdmCidade.setEditable(false);
        txtAdmCidade.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        getContentPane().add(txtAdmCidade);
        txtAdmCidade.setBounds(150, 390, 520, 30);

        try {
            ftxtAdmCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(ftxtAdmCEP);
        ftxtAdmCEP.setBounds(150, 350, 380, 30);

        btAdmBuscaCep.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        btAdmBuscaCep.setText("Buscar CEP");
        btAdmBuscaCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdmBuscaCepActionPerformed(evt);
            }
        });
        getContentPane().add(btAdmBuscaCep);
        btAdmBuscaCep.setBounds(530, 350, 140, 30);

        btAdmCadastrar.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        btAdmCadastrar.setText("Concuir Cadastro");
        btAdmCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdmCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btAdmCadastrar);
        btAdmCadastrar.setBounds(150, 440, 190, 60);

        btAdmCancel.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        btAdmCancel.setText("Cancelar");
        btAdmCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdmCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btAdmCancel);
        btAdmCancel.setBounds(400, 440, 190, 60);

        lbCadAdmBackground.setText("jLabel1");
        lbCadAdmBackground.setMaximumSize(new java.awt.Dimension(1280, 720));
        lbCadAdmBackground.setMinimumSize(new java.awt.Dimension(1280, 720));
        lbCadAdmBackground.setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().add(lbCadAdmBackground);
        lbCadAdmBackground.setBounds(0, 0, 1280, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btAdmCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdmCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btAdmCancelActionPerformed

    private void pwAdmSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwAdmSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwAdmSenhaActionPerformed

    private void pwAdmReSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwAdmReSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwAdmReSenhaActionPerformed

    private void btAdmCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdmCadastrarActionPerformed
        
        if(txtAdmNomeF.getText().matches("")
                 ||txtAdmEmail.getText().matches("")
                 ||txtAdmCidade.getText().matches("")
                || pwAdmSenha.getText().matches("")) {

            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }  else {

            try {
                loginControler cadastro = new loginControler();
                cadastro.cadastroAdm(this);
                
                
                
            } catch (SQLException sql) {

            }
            
            
            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
            this.setVisible(false);
        }
                
                
                
                
    }//GEN-LAST:event_btAdmCadastrarActionPerformed

    private void btAdmBuscaCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdmBuscaCepActionPerformed
        ViaCepService buscaCidade = new ViaCepService();
        String cepADM = ftxtAdmCEP.getText();
        
        Endereco endereco;
        try {
            endereco = ViaCepService.getEndereco(cepADM);
            
            String adm_cidade = endereco.getLocalidade();
            txtAdmCidade.setText(adm_cidade);
        } catch (IOException ex) {
            Logger.getLogger(telaCadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAdmBuscaCepActionPerformed

    
    
    
    public JFormattedTextField getFtxtAdmCnpj() {
        return ftxtAdmCnpj;
    }

    public void setFtxtAdmCnpj(JFormattedTextField ftxtAdmCnpj) {
        this.ftxtAdmCnpj = ftxtAdmCnpj;
    }

    public JFormattedTextField getFtxtAdmTelefone() {
        return ftxtAdmTelefone;
    }

    public void setFtxtAdmTelefone(JFormattedTextField ftxtAdmTelefone) {
        this.ftxtAdmTelefone = ftxtAdmTelefone;
    }

    public JPasswordField getPwAdmSenha() {
        return pwAdmSenha;
    }

    public void setPwAdmSenha(JPasswordField pwAdmSenha) {
        this.pwAdmSenha = pwAdmSenha;
    }

    public JTextField getTxtAdmCidade() {
        return txtAdmCidade;
    }

    public void setTxtAdmCidade(JTextField txtAdmCidade) {
        this.txtAdmCidade = txtAdmCidade;
    }

    public JTextField getTxtAdmEmail() {
        return txtAdmEmail;
    }

    public void setTxtAdmEmail(JTextField txtAdmEmail) {
        this.txtAdmEmail = txtAdmEmail;
    }

    public JTextField getTxtAdmNomeF() {
        return txtAdmNomeF;
    }

    public void setTxtAdmNomeF(JTextField txtAdmNomeF) {
        this.txtAdmNomeF = txtAdmNomeF;
    }

    public JTextField getTxtAdmRepres() {
        return txtAdmRepres;
    }

    /**
     * @param args the command line arguments
     */
    public void setTxtAdmRepres(JTextField txtAdmRepres) {
        this.txtAdmRepres = txtAdmRepres;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaCadastroBarbearia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaCadastroBarbearia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaCadastroBarbearia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaCadastroBarbearia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaCadastroBarbearia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdmBuscaCep;
    private javax.swing.JButton btAdmCadastrar;
    private javax.swing.JButton btAdmCancel;
    private javax.swing.JFormattedTextField ftxtAdmCEP;
    private javax.swing.JFormattedTextField ftxtAdmCnpj;
    private javax.swing.JFormattedTextField ftxtAdmTelefone;
    private javax.swing.JLabel lbAdmCep;
    private javax.swing.JLabel lbAdmCidade;
    private javax.swing.JLabel lbAdmEmail;
    private javax.swing.JLabel lbAdmNomeRepres;
    private javax.swing.JLabel lbAdmRepSenha;
    private javax.swing.JLabel lbAdmSenha;
    private javax.swing.JLabel lbAdmTelefone;
    private javax.swing.JLabel lbCadAdmBackground;
    private javax.swing.JLabel lbCnpj;
    private javax.swing.JLabel lbNomeFanstasia;
    private javax.swing.JPasswordField pwAdmReSenha;
    private javax.swing.JPasswordField pwAdmSenha;
    private javax.swing.JTextField txtAdmCidade;
    private javax.swing.JTextField txtAdmEmail;
    private javax.swing.JTextField txtAdmNomeF;
    private javax.swing.JTextField txtAdmRepres;
    // End of variables declaration//GEN-END:variables
}
