/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.unifio.barbersoft;

/**
 *
 * @author educo
 */
public class telaInicialAdm extends javax.swing.JFrame {

    /**
     * Creates new form telaInicialAdm
     */
    public telaInicialAdm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgendamento = new javax.swing.JButton();
        btnConfHorario = new javax.swing.JButton();
        btnProfissionais = new javax.swing.JButton();
        btnServicos = new javax.swing.JButton();
        btnClientesAdm = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lbAdmTelefone1 = new javax.swing.JLabel();
        lbAdmTelefone2 = new javax.swing.JLabel();
        lbAdmTelefone3 = new javax.swing.JLabel();
        lbAdmTelefone4 = new javax.swing.JLabel();
        lbAdmTelefone5 = new javax.swing.JLabel();
        lbAdmTelefone6 = new javax.swing.JLabel();
        lbAdmTelefone7 = new javax.swing.JLabel();
        lbAdmTelefone8 = new javax.swing.JLabel();
        lbAdmTelefone9 = new javax.swing.JLabel();
        lbAdmTelefone10 = new javax.swing.JLabel();
        lbCliBackGround = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        btnAgendamento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAgendamento.setForeground(new java.awt.Color(0, 0, 0));
        btnAgendamento.setText("BARBEARIAS");
        btnAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendamentoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgendamento);
        btnAgendamento.setBounds(50, 470, 330, 140);

        btnConfHorario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnConfHorario.setForeground(new java.awt.Color(0, 0, 0));
        btnConfHorario.setText("MEUS AGENDAMENTOS");
        btnConfHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfHorarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfHorario);
        btnConfHorario.setBounds(450, 160, 330, 140);

        btnProfissionais.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnProfissionais.setForeground(new java.awt.Color(0, 0, 0));
        btnProfissionais.setText("AGENDAR SERVIÇO");
        btnProfissionais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfissionaisActionPerformed(evt);
            }
        });
        getContentPane().add(btnProfissionais);
        btnProfissionais.setBounds(50, 160, 330, 140);

        btnServicos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnServicos.setForeground(new java.awt.Color(0, 0, 0));
        btnServicos.setText("OPÇÃO DE PERFIL");
        btnServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicosActionPerformed(evt);
            }
        });
        getContentPane().add(btnServicos);
        btnServicos.setBounds(450, 470, 330, 140);

        btnClientesAdm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClientesAdm.setForeground(new java.awt.Color(0, 0, 0));
        btnClientesAdm.setText("SUPORTE");
        btnClientesAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesAdmActionPerformed(evt);
            }
        });
        getContentPane().add(btnClientesAdm);
        btnClientesAdm.setBounds(850, 470, 330, 140);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Eduardo\\Documents\\GitHub\\Faculdade-JAVA\\Java\\Projetos Faculdade\\Projeto Integrador\\BarberSoft\\src\\main\\java\\BarberIMG\\icon50.png")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(810, 80, 450, 340);

        lbAdmTelefone1.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbAdmTelefone1.setForeground(new java.awt.Color(0, 0, 0));
        lbAdmTelefone1.setText(" disponiveis por cidade.");
        getContentPane().add(lbAdmTelefone1);
        lbAdmTelefone1.setBounds(120, 630, 200, 30);

        lbAdmTelefone2.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbAdmTelefone2.setForeground(new java.awt.Color(0, 0, 0));
        lbAdmTelefone2.setText("Visualize agendamentos");
        getContentPane().add(lbAdmTelefone2);
        lbAdmTelefone2.setBounds(530, 300, 200, 30);

        lbAdmTelefone3.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbAdmTelefone3.setForeground(new java.awt.Color(0, 0, 0));
        lbAdmTelefone3.setText("Realize seu agendamento!");
        getContentPane().add(lbAdmTelefone3);
        lbAdmTelefone3.setBounds(110, 300, 240, 30);

        lbAdmTelefone4.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbAdmTelefone4.setForeground(new java.awt.Color(0, 0, 0));
        lbAdmTelefone4.setText("dados pessoais");
        getContentPane().add(lbAdmTelefone4);
        lbAdmTelefone4.setBounds(560, 630, 150, 20);

        lbAdmTelefone5.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbAdmTelefone5.setForeground(new java.awt.Color(0, 0, 0));
        lbAdmTelefone5.setText("Visualize as Barbearias");
        getContentPane().add(lbAdmTelefone5);
        lbAdmTelefone5.setBounds(120, 610, 200, 30);

        lbAdmTelefone6.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbAdmTelefone6.setForeground(new java.awt.Color(0, 0, 0));
        lbAdmTelefone6.setText("com App.");
        getContentPane().add(lbAdmTelefone6);
        lbAdmTelefone6.setBounds(980, 630, 80, 30);

        lbAdmTelefone7.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbAdmTelefone7.setForeground(new java.awt.Color(0, 0, 0));
        lbAdmTelefone7.setText("Visualize e altere seus");
        getContentPane().add(lbAdmTelefone7);
        lbAdmTelefone7.setBounds(530, 610, 200, 20);

        lbAdmTelefone8.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbAdmTelefone8.setForeground(new java.awt.Color(0, 0, 0));
        lbAdmTelefone8.setText("Dúvidas e problemas");
        getContentPane().add(lbAdmTelefone8);
        lbAdmTelefone8.setBounds(940, 610, 200, 30);

        lbAdmTelefone9.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbAdmTelefone9.setForeground(new java.awt.Color(0, 0, 0));
        lbAdmTelefone9.setText("realizados.");
        getContentPane().add(lbAdmTelefone9);
        lbAdmTelefone9.setBounds(580, 320, 100, 30);

        lbAdmTelefone10.setFont(new java.awt.Font("Perpetua", 0, 36)); // NOI18N
        lbAdmTelefone10.setForeground(new java.awt.Color(0, 0, 0));
        lbAdmTelefone10.setText("  Seja bem vindo nome_usuario");
        lbAdmTelefone10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lbAdmTelefone10);
        lbAdmTelefone10.setBounds(-10, 20, 1320, 60);

        lbCliBackGround.setForeground(new java.awt.Color(0, 0, 0));
        lbCliBackGround.setIcon(new javax.swing.ImageIcon("C:\\Users\\Eduardo\\Documents\\GitHub\\Faculdade-JAVA\\Java\\Projetos Faculdade\\Projeto Integrador\\BarberSoft\\src\\main\\java\\BarberIMG\\bkgr_img.png")); // NOI18N
        getContentPane().add(lbCliBackGround);
        lbCliBackGround.setBounds(0, -40, 1280, 760);

        jMenu2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jMenu2.setText("Opções do APP");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMenu1.setText("Opções de idioma");
        jMenu2.add(jMenu1);

        jMenu3.setText("Opções de vizualização");
        jMenu2.add(jMenu3);

        jMenu4.setText("Sair da conta");
        jMenu2.add(jMenu4);

        jMenu5.setText("Sair do APP");
        jMenu2.add(jMenu5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendamentoActionPerformed
      
        telaAgendamentoAdm telaAgendamentoAdm = new telaAgendamentoAdm();
        telaAgendamentoAdm.setVisible(true);
    }//GEN-LAST:event_btnAgendamentoActionPerformed

    private void btnConfHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfHorarioActionPerformed
      
        telaConfiguracaoHorarioAdm telaConfiguracaoHorarioAdm = new telaConfiguracaoHorarioAdm();
        telaConfiguracaoHorarioAdm.setVisible(true);
        
    }//GEN-LAST:event_btnConfHorarioActionPerformed

    private void btnProfissionaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfissionaisActionPerformed
       
        telaProfissionaisAdm telaProfissionaisAdm = new telaProfissionaisAdm();
        telaProfissionaisAdm.setVisible(true);
        
    }//GEN-LAST:event_btnProfissionaisActionPerformed

    private void btnServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicosActionPerformed
      
        telaServicosAdm telaServicosAdm = new telaServicosAdm();
        telaServicosAdm.setVisible(true);
    }//GEN-LAST:event_btnServicosActionPerformed

    private void btnClientesAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesAdmActionPerformed

        telaClientesAdm telaClientesAdm = new telaClientesAdm();
        telaClientesAdm.setVisible(true);
    }//GEN-LAST:event_btnClientesAdmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaInicialAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaInicialAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaInicialAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaInicialAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaInicialAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendamento;
    private javax.swing.JButton btnClientesAdm;
    private javax.swing.JButton btnConfHorario;
    private javax.swing.JButton btnProfissionais;
    private javax.swing.JButton btnServicos;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbAdmTelefone1;
    private javax.swing.JLabel lbAdmTelefone10;
    private javax.swing.JLabel lbAdmTelefone2;
    private javax.swing.JLabel lbAdmTelefone3;
    private javax.swing.JLabel lbAdmTelefone4;
    private javax.swing.JLabel lbAdmTelefone5;
    private javax.swing.JLabel lbAdmTelefone6;
    private javax.swing.JLabel lbAdmTelefone7;
    private javax.swing.JLabel lbAdmTelefone8;
    private javax.swing.JLabel lbAdmTelefone9;
    private javax.swing.JLabel lbCliBackGround;
    // End of variables declaration//GEN-END:variables
}
