 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.unifio.barbersoft;

import LoginBarbersoftController.loginControler;
import LoginBarbersoftDAO.loginDAO;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.sql.SQLException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.UIManager;

/**
 *
 * @author educo
 */
public class telaI1Login extends javax.swing.JFrame {

    /**
     * Creates new form telaInicial
     */
    public telaI1Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbLogin = new javax.swing.JLabel();
        lbCadastro = new javax.swing.JLabel();
        txtEmailLogin = new javax.swing.JTextField();
        pwSenhaLogin = new javax.swing.JPasswordField();
        btLoginCLI = new javax.swing.JButton();
        btLoginADM = new javax.swing.JButton();
        btRegistro = new javax.swing.JButton();
        btRegistro1 = new javax.swing.JButton();
        lbBackgroundCli = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));

        lbLogin.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        lbLogin.setText("Email:");

        lbCadastro.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        lbCadastro.setText("Senha:");

        txtEmailLogin.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N

        pwSenhaLogin.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        pwSenhaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwSenhaLoginActionPerformed(evt);
            }
        });

        btLoginCLI.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        btLoginCLI.setText("Login Cliente");
        btLoginCLI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginCLIActionPerformed(evt);
            }
        });

        btLoginADM.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        btLoginADM.setText("Login Barbearia");
        btLoginADM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginADMActionPerformed(evt);
            }
        });

        btRegistro.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        btRegistro.setText("Cadastro Barbearia");
        btRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistroActionPerformed(evt);
            }
        });

        btRegistro1.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        btRegistro1.setText("Cadastro Cliente");
        btRegistro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistro1ActionPerformed(evt);
            }
        });

        lbBackgroundCli.setText("jLabel2");
        lbBackgroundCli.setMaximumSize(new java.awt.Dimension(1280, 720));
        lbBackgroundCli.setMinimumSize(new java.awt.Dimension(1280, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(pwSenhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(btLoginADM, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(btRegistro1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(txtEmailLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(btLoginCLI, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lbLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lbBackgroundCli, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(pwSenhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btLoginADM, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btRegistro1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(txtEmailLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(btLoginCLI, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lbLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(lbCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lbBackgroundCli, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btLoginADMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginADMActionPerformed
        if (txtEmailLogin.getText().matches("") || pwSenhaLogin.getText().matches("")) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
            
        } else {

            try {
                loginControler LoginAdm = new loginControler();
                LoginAdm.loginAdm(this);
                
            } catch (SQLException ex) {
                Logger.getLogger(telaI1Login.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            

            
        }
    }//GEN-LAST:event_btLoginADMActionPerformed

    private void pwSenhaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwSenhaLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwSenhaLoginActionPerformed

    private void btLoginCLIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginCLIActionPerformed
       
        
        
        if(txtEmailLogin.getText().matches("") || pwSenhaLogin.getText().matches("")){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        } else {
        
            try {
                loginControler LoginCLiente = new loginControler();
                LoginCLiente.loginUsuario(this);
                              
            } catch (SQLException ex) {
                Logger.getLogger(telaI1Login.class.getName()).log(Level.SEVERE, null, ex);
            }
            
           
            

             
        }
        
        
    }//GEN-LAST:event_btLoginCLIActionPerformed

    private void btRegistro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistro1ActionPerformed
        telaCadastroCliente telaDeCadastroCliente = new  telaCadastroCliente();
        telaDeCadastroCliente.setVisible(true);
    }//GEN-LAST:event_btRegistro1ActionPerformed

    private void btRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistroActionPerformed
        telaCadastroBarbearia telaDeCadastroBarber = new  telaCadastroBarbearia();
        telaDeCadastroBarber.setVisible(true);
    }//GEN-LAST:event_btRegistroActionPerformed

    public JPasswordField getPwSenhaLogin() {
        return pwSenhaLogin;
    }

    public void setPwSenhaLogin(JPasswordField pwSenhaLogin) {
        this.pwSenhaLogin = pwSenhaLogin;
    }

    public JTextField getTxtEmailLogin() {
        return txtEmailLogin;
    }

    public void setTxtEmailLogin(JTextField txtEmailLogin) {
        this.txtEmailLogin = txtEmailLogin;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.texture.TextureLookAndFeel");
        } catch (Exception e) {
        }
  
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaI1Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaI1Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaI1Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaI1Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaI1Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btLoginADM;
    public javax.swing.JButton btLoginCLI;
    public javax.swing.JButton btRegistro;
    public javax.swing.JButton btRegistro1;
    public javax.swing.JLabel lbBackgroundCli;
    public javax.swing.JLabel lbCadastro;
    public javax.swing.JLabel lbLogin;
    public javax.swing.JPasswordField pwSenhaLogin;
    public javax.swing.JTextField txtEmailLogin;
    // End of variables declaration//GEN-END:variables
}
