/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.unifio.barbersoft;

/**
 *
 * @author educo
 */
public class telaInicialAdm extends javax.swing.JFrame {

    /**
     * Creates new form telaInicialAdm
     */
    public telaInicialAdm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgendamento = new javax.swing.JButton();
        btnConfHorario = new javax.swing.JButton();
        btnProfissionais = new javax.swing.JButton();
        btnServicos = new javax.swing.JButton();
        btnClientesAdm = new javax.swing.JButton();
        lbLogo = new javax.swing.JLabel();
        lbTextoAgend = new javax.swing.JLabel();
        lbTextoMeusA = new javax.swing.JLabel();
        lbTextoMeusAgen = new javax.swing.JLabel();
        lbTextoBarb = new javax.swing.JLabel();
        lbTextoBarbe = new javax.swing.JLabel();
        lbTextoOpcao = new javax.swing.JLabel();
        lbTextoOpcaoDe = new javax.swing.JLabel();
        lbTextoSuporte = new javax.swing.JLabel();
        lbTextoSupor = new javax.swing.JLabel();
        lbFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnAgendamento.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnAgendamento.setForeground(new java.awt.Color(0, 0, 0));
        btnAgendamento.setText("BARBEARIAS");
        btnAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendamentoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgendamento);
        btnAgendamento.setBounds(20, 290, 170, 75);

        btnConfHorario.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnConfHorario.setForeground(new java.awt.Color(0, 0, 0));
        btnConfHorario.setText("MEUS AGENDAMENTOS");
        btnConfHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfHorarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfHorario);
        btnConfHorario.setBounds(230, 70, 170, 75);

        btnProfissionais.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnProfissionais.setForeground(new java.awt.Color(0, 0, 0));
        btnProfissionais.setText("AGENDAR SERVIÇO");
        btnProfissionais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfissionaisActionPerformed(evt);
            }
        });
        getContentPane().add(btnProfissionais);
        btnProfissionais.setBounds(20, 70, 170, 75);

        btnServicos.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnServicos.setForeground(new java.awt.Color(0, 0, 0));
        btnServicos.setText("OPÇÃO DE PERFIL");
        btnServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicosActionPerformed(evt);
            }
        });
        getContentPane().add(btnServicos);
        btnServicos.setBounds(220, 290, 170, 75);

        btnClientesAdm.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnClientesAdm.setForeground(new java.awt.Color(0, 0, 0));
        btnClientesAdm.setText("SUPORTE");
        btnClientesAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesAdmActionPerformed(evt);
            }
        });
        getContentPane().add(btnClientesAdm);
        btnClientesAdm.setBounds(480, 290, 170, 75);

        lbLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rafael\\Documents\\GitHub\\Faculdade-JAVA\\Java\\Projetos Faculdade\\Projeto Integrador\\BarberSoft\\src\\main\\java\\BarberIMG\\icon30.png")); // NOI18N
        lbLogo.setText("jLabel1");
        getContentPane().add(lbLogo);
        lbLogo.setBounds(420, 0, 290, 260);

        lbTextoAgend.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lbTextoAgend.setForeground(new java.awt.Color(0, 0, 0));
        lbTextoAgend.setText("Realize seu agendamento!");
        getContentPane().add(lbTextoAgend);
        lbTextoAgend.setBounds(30, 150, 150, 15);

        lbTextoMeusA.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lbTextoMeusA.setForeground(new java.awt.Color(0, 0, 0));
        lbTextoMeusA.setText("Visualize agendamentos");
        getContentPane().add(lbTextoMeusA);
        lbTextoMeusA.setBounds(250, 150, 160, 15);

        lbTextoMeusAgen.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lbTextoMeusAgen.setForeground(new java.awt.Color(0, 0, 0));
        lbTextoMeusAgen.setText("realizados.");
        getContentPane().add(lbTextoMeusAgen);
        lbTextoMeusAgen.setBounds(280, 170, 70, 15);

        lbTextoBarb.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lbTextoBarb.setForeground(new java.awt.Color(0, 0, 0));
        lbTextoBarb.setText("Visualize as Barbearias");
        getContentPane().add(lbTextoBarb);
        lbTextoBarb.setBounds(40, 370, 140, 15);

        lbTextoBarbe.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lbTextoBarbe.setForeground(new java.awt.Color(0, 0, 0));
        lbTextoBarbe.setText("disponiveis por cidade.");
        getContentPane().add(lbTextoBarbe);
        lbTextoBarbe.setBounds(40, 385, 140, 15);

        lbTextoOpcao.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lbTextoOpcao.setForeground(new java.awt.Color(0, 0, 0));
        lbTextoOpcao.setText("Visualize e altere seus");
        getContentPane().add(lbTextoOpcao);
        lbTextoOpcao.setBounds(240, 370, 130, 15);

        lbTextoOpcaoDe.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lbTextoOpcaoDe.setForeground(new java.awt.Color(0, 0, 0));
        lbTextoOpcaoDe.setText("dados pessoais.");
        getContentPane().add(lbTextoOpcaoDe);
        lbTextoOpcaoDe.setBounds(250, 385, 100, 15);

        lbTextoSuporte.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lbTextoSuporte.setForeground(new java.awt.Color(0, 0, 0));
        lbTextoSuporte.setText("Em caso de problemas");
        getContentPane().add(lbTextoSuporte);
        lbTextoSuporte.setBounds(500, 370, 130, 15);

        lbTextoSupor.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lbTextoSupor.setForeground(new java.awt.Color(0, 0, 0));
        lbTextoSupor.setText("com App.");
        getContentPane().add(lbTextoSupor);
        lbTextoSupor.setBounds(530, 385, 60, 15);

        lbFundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rafael\\Documents\\GitHub\\Faculdade-JAVA\\Java\\Projetos Faculdade\\Projeto Integrador\\BarberSoft\\src\\main\\java\\BarberIMG\\bkgr_img.png")); // NOI18N
        lbFundo.setText("jLabel2");
        lbFundo.setMaximumSize(new java.awt.Dimension(770, 510));
        lbFundo.setMinimumSize(new java.awt.Dimension(770, 510));
        lbFundo.setPreferredSize(new java.awt.Dimension(770, 510));
        getContentPane().add(lbFundo);
        lbFundo.setBounds(-6, -20, 690, 470);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendamentoActionPerformed
      
        telaAgendamentoAdm telaAgendamentoAdm = new telaAgendamentoAdm();
        telaAgendamentoAdm.setVisible(true);
    }//GEN-LAST:event_btnAgendamentoActionPerformed

    private void btnConfHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfHorarioActionPerformed
      
        telaConfiguracaoHorarioAdm telaConfiguracaoHorarioAdm = new telaConfiguracaoHorarioAdm();
        telaConfiguracaoHorarioAdm.setVisible(true);
        
    }//GEN-LAST:event_btnConfHorarioActionPerformed

    private void btnProfissionaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfissionaisActionPerformed
       
        telaProfissionaisAdm telaProfissionaisAdm = new telaProfissionaisAdm();
        telaProfissionaisAdm.setVisible(true);
        
    }//GEN-LAST:event_btnProfissionaisActionPerformed

    private void btnServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicosActionPerformed
      
        telaServicosAdm telaServicosAdm = new telaServicosAdm();
        telaServicosAdm.setVisible(true);
    }//GEN-LAST:event_btnServicosActionPerformed

    private void btnClientesAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesAdmActionPerformed

        telaClientesAdm telaClientesAdm = new telaClientesAdm();
        telaClientesAdm.setVisible(true);
    }//GEN-LAST:event_btnClientesAdmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaInicialAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaInicialAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaInicialAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaInicialAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaInicialAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendamento;
    private javax.swing.JButton btnClientesAdm;
    private javax.swing.JButton btnConfHorario;
    private javax.swing.JButton btnProfissionais;
    private javax.swing.JButton btnServicos;
    private javax.swing.JLabel lbFundo;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbTextoAgend;
    private javax.swing.JLabel lbTextoBarb;
    private javax.swing.JLabel lbTextoBarbe;
    private javax.swing.JLabel lbTextoMeusA;
    private javax.swing.JLabel lbTextoMeusAgen;
    private javax.swing.JLabel lbTextoOpcao;
    private javax.swing.JLabel lbTextoOpcaoDe;
    private javax.swing.JLabel lbTextoSupor;
    private javax.swing.JLabel lbTextoSuporte;
    // End of variables declaration//GEN-END:variables
}
